### GET /albums
curl http://localhost:8080/albums \
    -- request "GET"

### GET /albums/id
curl http://localhost:8080/albums/5 \
    -- request "GET"
### POST /albums
curl http://localhost:8080/albums \
    --include \
    --header "Content-Type: application/json" \
    --request "POST" \
    --data '{"id": 0,"title": "The Modern Sound of Betty Carter","artist": "Betty Carter","price": 49.99}'
### DELETE /album/id
curl http://localhost:8080/albums/5 \
    --request "DELETE"